// <auto-generated />
using System;
using EquipoAleatorio.AccesoDatos.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EquipoAleatorio.AccesoDatos.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220302044927_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.14")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EquipoAleatorio.Entidades.Contexto.Jugador", b =>
                {
                    b.Property<int>("IdJugador")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NombreJugador")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("TipoJugadorIdTipoJugador")
                        .HasColumnType("int");

                    b.HasKey("IdJugador");

                    b.HasIndex("NombreJugador")
                        .IsUnique()
                        .HasFilter("[NombreJugador] IS NOT NULL");

                    b.HasIndex("TipoJugadorIdTipoJugador");

                    b.ToTable("Jugador");
                });

            modelBuilder.Entity("EquipoAleatorio.Entidades.Contexto.TipoJugador", b =>
                {
                    b.Property<int>("IdTipoJugador")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NombreTipoJugador")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("IdTipoJugador");

                    b.HasIndex("NombreTipoJugador")
                        .IsUnique()
                        .HasFilter("[NombreTipoJugador] IS NOT NULL");

                    b.ToTable("TipoJugador");
                });

            modelBuilder.Entity("EquipoAleatorio.Entidades.Contexto.Jugador", b =>
                {
                    b.HasOne("EquipoAleatorio.Entidades.Contexto.TipoJugador", "TipoJugador")
                        .WithMany()
                        .HasForeignKey("TipoJugadorIdTipoJugador");

                    b.Navigation("TipoJugador");
                });
#pragma warning restore 612, 618
        }
    }
}
